### ISSUE TITLE
API entity lookups

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#34]
When trying to work out an `api.py` for Components, I realized that there are an awkwardly large number of ways you can uniquely look up a Component. Namely:

* ID (primary key): Best for in-database references. Immutable.
* UUID (unique): Best for external references, like data entries in other systems. Also immutable. Possibly useful for import/export use cases across instances.
* LearningPackage + identifier: Most human readable thing, but _mutable_, and not good for storing references to, but could make for pretty URLs and sensible export files.

And that last use case gets weird, because there are multiple ways to look up a LearningPackage. I started to get these api functions that were just really lookup variants. It made me think of just going straight to models, but then I was wondering if we could try to hide some of that behind some typing conventions. So say we had something that looked like this:

```python
from typing import Union, Tuple
from uuid import UUID

LearningPackageIdLookup = int
LearningPackageUUIDLookup = UUID
LearningPackageIdentifierLookup = str
LearningPackageLookup = Union[
    LearningPackageIdLookup,
    LearningPackageUUIDLookup,
    LearningPackageIdentifierLookup
]

ComponentIdLookup = int
ComponentUUIDLookup = UUID
ComponentIdentifierLookup = Tuple[LearningPackageLookup, str]
ComponentLookup = Union[
    ComponentIdLookup,
    ComponentUUIDLookup,
    ComponentIdentifierLookup,
]

ComponentVersionIdLookup = int
ComponentVersionUUIDLookup = UUID
ComponentVersionNumLookup = Tuple[ComponentLookup, int]
ComponentVersionLookup = Union[
    ComponentVersionIdLookup,
    ComponentVersionUUIDLookup,
    ComponentVersionNumLookup,
]


def get_component_version(lookup: ComponentVersionLookup) -> ComponentVersionData:
    # ...

```

The inside of that would be a number of `isinstance` calls to figure out what queries need to be fed to the ORM to get what we want (we can't use `match` until Python 3.10).

So people would call it like:

```python
get_component_version(20)

get_component_version(some_uuid)

get_component_version(ComponentVersionNumLookup(component_lookup, 4))
```

I haven't really seen this pattern before though. Do you think it'd be too confusing?

FYI: @bradenmacdonald, @kdmccormick, @feanil

**Comment by bradenmacdonald** [comment]
In general, I'm fine with any approach as long as we define the types very clearly like you're doing here!

This seems like a nice way to go, with the caveat that if every function accepts every ID type, developers may not always use the "best" choice in every situation, e.g. may pass around UUIDs in purely internal code, just because it is easy and it works, rather than converting to internal IDs. So it _may_ be helpful to use a more limited set of types on certain APIs depending on their use case, _or_ to rename your types to `LearningPackageInternalId` (int), `LearningPackageExternalUUID`, and `LearningPackageMutableFriendlyId` to help encourage thoughtful use of each one?  Just a passing idea, not something I'm very sure about.

Another thing to be careful of is that caches should only accept one type of ID as the cache key, to avoid obvious problems if the same thing is stored in the cache under different keys. This could mean that `@lru_cache` and friends aren't as optimal with these types of API functions, but that's not necessarily a big deal - just means the cache logic is in a different place, e.g. inside the function after the key has been dereferenced.

The one thing I would definitely recommend though is using `NamedTuple` instead of `Tuple`. With your code sketch above, it's not actually possible to instantiate an ID using the syntax `ComponentVersionNumLookup(component_lookup, 4)` because the `Tuple` type cannot be instantiated. But if you use NamedTuple, not only can you use the type directly to instantiate things, but you get labelled fields in the string representation and you can use named fields when instantiating the key if you want:

```python
>>> class ComponentVersionNumLookup(NamedTuple):
...     component: ComponentLookup
...     version: int
... 
>>> ComponentVersionNumLookup(15, 4)
ComponentVersionNumLookup(component=15, version=4)
>>> ComponentVersionNumLookup(component=15, version=4)
ComponentVersionNumLookup(component=15, version=4)
```

**Comment by feanil** [comment]
The identifier lookup is a bit strange because `ComponentLookup` can be an `int`, a `UUID`, or a `str`

```python
>>> ComponentVersionNumLookup(15, 4)
>>> ComponentVersionNumLookup('5982b8e3-67ac-4559-aacd-8787a2761bf0', 4)
>>> ComponentVersionNumLookup(ComponentIdentifierLookup("package_id", "component_id"), 4)
```

Looking at it this way, I wondered if instead of putting all the intelligence in the `get_component_version` call if it made sense to make there be just a class for each type of identifier which would take any of the ways of identifying the package and track it using the canonical ID internally? This would be essentially a simplified class compared to the full model that just canonicalizes the the various identifiers and then the logic in `get_component_version` looks a lot simpler.

That said, I think @bradenmacdonald 's point about caching still stands and we'll have to be careful how we create the cache keys.

Side note: This feels like OpaqueKeys territory and I'm cool with not making it more complicated to avoid some of the caching and object explosion issues we ran into with Opaque keys.

> This seems like a nice way to go, with the caveat that if every function accepts every ID type, developers may not always use the "best" choice in every situation, e.g. may pass around UUIDs in purely internal code, just because it is easy and it works, rather than converting to internal IDs. So it _may_ be helpful to use a more limited set of types on certain APIs depending on their use case, _or_ to rename your types to `LearningPackageInternalId` (int), `LearningPackageExternalUUID`, and `LearningPackageMutableFriendlyId` to help encourage thoughtful use of each one? Just a passing idea, not something I'm very sure about.

I like the idea of making the use cases more clear in the naming.

---
On a different tack:  Why have 3 ways of identifying the component?  The `*IdentifierLookup` feel more like they're part of the presentation layer and the numeric Id seems redundant if you have a UUID.  Is it useful to have an ordered key for components?  Why not reduce to just supporting lookups via UUID?

**Comment by kdmccormick** [comment]
Sorry for the late input. I have to say that I think you are [going against your own advice here](https://medium.com/@dormsbee/xblock-lessons-field-data-complexity-2ef32d961b97):
> After years of working together, a fellow architect at edX once told me that he had figured out our core philosophical disagreement on API design. We actually agree more often than not, but when we disagree it’s usually because he’s willing to tolerate more implementation complexity if it yields a simpler interface for the API consumer. My bias is to keep the overall system simpler, even if it means placing a higher burden on the consumer (i.e. I’m in the New Jersey camp of [Worse Is Better](https://www.jwz.org/doc/worse-is-better.html)).

Rather than having a single responsibility, like *look up a component by UUID*, the `get_component_version` function would need to *convert an human-readable identifier to an ID and/or look up a component by UUID and/or look up the component by ID*. None of these simplifying assumptions would be true of `get_component_version`:
* Given the same argument, the function will always return the same component.
* Given two different arguments, the function will return two different components.

I have to go to lunch now, but I'll comment later with some more thoughts on what this could look like without using `Union` argument types.

**Comment by kdmccormick** [comment]
(Do you have any example code that uses any of these APIs? It's possible that your original proposal makes total sense when put in context, but that I'm having trouble seeing that just from the type signatures.)

Echoing @feanil , I think it'd be good to settle on a canonical ID for the component, probably UUID. I'd also like to understand better the difference between LearningPackage+Identifier vs UUID as a reference:

> LearningPackage + identifier: Most human readable thing, but mutable, and not good for storing references to, but could make for pretty URLs and sensible export files.

I assume that a LearningPackage+Identifer does not refer to a mutable Component, but rather it refers to a \<Something\> where \<Something\> is a mutable reference to a Component. Do you have a sense of what that \<Something\> is? Could we have a separate API function whose job is to dereference a \<Something\> into a concrete Component UUID?

Regarding database ID... that would probably only be used by apps which skip api.py and just directly use the models, right? Given that, would the API need to accept database ID at all?

**Comment by ormsbee** [comment]
> I assume that a LearningPackage+Identifer does not refer to a mutable Component, but rather it refers to a <Something> where <Something> is a mutable reference to a Component. Do you have a sense of what that <Something> is? Could we have a separate API function whose job is to dereference a <Something> into a concrete Component UUID?

This is mainly about being able to change things like CourseKeys and UsageKeys without breaking everything–something that's bitten us a number of times at edX. I don't expect we'll use that often, but I want the data model to support it. Having a method that does the conversion from this to a UUID is straightforward enough, but I expect that it will be a very common way to do querying (because that's likely what we'd have in a URL), and I didn't want to do the extra lookups. It doesn't matter as much for individual lookups, but I could see that practice leading to N+1 query pain later on.

> Regarding database ID... that would probably only be used by apps which skip api.py and just directly use the models, right? Given that, would the API need to accept database ID at all?

Yeah, I was asking myself that exact same question, and it's made me sort of question what it is that the API layer for the Learning Core is trying to accomplish. For instance:

* I don't want to re-implement the Django ORM's queryset API.
* I do want to strongly discourage people manually saving models or otherwise altering state.
* I would prefer that people not be able to shoot themselves in the foot with various query patterns, e.g. sort by an unindexed field on 5 billion records.
* I would *like* to be able to cleanly stub out data for certain API tests, and not require database roundtrips for those.

I've played a little with piggy-backing on that API, where it does queries the same way but converts those to attrs objects instead of full models at the end. One of the things I'd really like to do is to be able to compose querysets. For instance, if I have data attached to a certain queryset of Components, I'd like to be able to do something like:

```python
# TaggedComponent would be a 1:1 model that the tagging API hangs
# tag data off of for each Component.
def get_tagged_components(components: QuerySet):  
    return map_to_attrs(TaggedComponent, components.select_related("tagged_component"))
```

At the same time, there are libraries like [django-readers](https://www.django-readers.org/) which I still need to take a closer look at.

I think the upshot is that I'm going to punt a little longer on the API layer and see what query patterns emerge.

**Comment by kdmccormick** [comment]
> This is mainly about being able to change things like CourseKeys and UsageKeys without breaking everything–something that's bitten us a number of times at edX. I don't expect we'll use that often, but I want the data model to support it.

The begs somewhat of an existential question about what CourseKeys are. It seems like they try to serve two purposes at once:
1. a data-level identifier
2. a presentation-level nicety, like a URL slug

The desire to cleanly change CourseKeys makes me think we want them to move towards them being just (2), not (1). In that case, we want an API that:
* encourages folks to convert human-readable Keys into IDs or UUIDs as early as possible
* encourages them to convert IDs/UUIDs back into Keys as late as possible
* discourages them from ever joining on human-readable Keys.

It reminds me of the industry's saga with `username`. For a long time, it was both a data-level identifier and a user-facing thing. The desire to change usernames was at odds with that. Now, it's all decoupled: some internal user_id is the immutable data-level identifier, and the username is just a mutable "display name".

> One of the things I'd really like to do is to be able to compose querysets. For instance, if I have data attached to a certain queryset of Components, I'd like to be able to do something like: ...

Yeah, that makes a lot of sense. Being able to pass QuerySets in like that both looks efficient and very eleganat.

Models can be made readonly by subclassing them and overriding a few methods. Maybe we could embrace a pattern of having a readonly version of all model classes, and then returning readonly model instances from API functions.

**Comment by ormsbee** [comment]
For now, the API mostly uses primary keys internally, except some functions that are explicitly labeled as using keys. I'm closing this for now, with the understanding that we might revisit it if when/if the current conventions become a problem.
